server:
  port: 9005

spring:
  mandatory-file-encoding: UTF-8
  thymeleaf:
    suffix: .html
    cache: false
    encoding: UTF-8
    prefix: classpath:/templates/

logging:
    level:
        org.hibernate.engine.jdbc.env.internal.LobCreatorBuilderImpl: ERROR
